{{- if .Values.platform.properties.sso.encryptionSecret.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.platform.properties.sso.encryptionSecret.secret.name | quote }}
data:
  {{ .Values.platform.properties.sso.encryptionSecret.secret.key | quote }}: {{ .Values.platform.properties.sso.encryptionSecret.literal | b64enc | quote }}
{{- end }}