{{- if .Values.janitor.properties.gitlabToken.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.janitor.properties.gitlabToken.secret.name | quote }}
data:
  {{ .Values.janitor.properties.gitlabToken.secret.key | quote }}: {{ .Values.janitor.properties.gitlabToken.literal | b64enc | quote }}
{{- end }}