apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nmaas-shell-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "watch"]

