{{- if .Values.platform.properties.postgresql.password.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.platform.properties.postgresql.password.secret.name | quote }}
data:
  {{ .Values.platform.properties.postgresql.password.secret.key | quote }}: {{ .Values.platform.properties.postgresql.password.literal | b64enc | quote }}
{{- end }}