{{- if and .Values.postfix.properties.smtp.host.literal .Values.postfix.properties.smtp.username.literal .Values.postfix.properties.smtp.password.literal  }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.postfix.properties.smtp.secretName | quote }}
data:
  {{ .Values.postfix.properties.smtp.host.secret.key | quote }}: {{ .Values.postfix.properties.smtp.host.literal | b64enc | quote }}
  {{ .Values.postfix.properties.smtp.username.secret.key | quote }}: {{ .Values.postfix.properties.smtp.username.literal | b64enc | quote }}
  {{ .Values.postfix.properties.smtp.password.secret.key | quote }}: {{ .Values.postfix.properties.smtp.password.literal | b64enc | quote }}
{{- end }}