{{- if .Values.portal.properties.captchaKey.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.portal.properties.captchaKey.secret.name | quote }}
data:
  {{ .Values.portal.properties.captchaKey.secret.key | quote }}: {{ .Values.portal.properties.captchaKey.literal | b64enc | quote }}
{{- end }}