{{- if .Values.portal.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.portal.name }}
  labels:
    app: {{ .Values.portal.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.portal.name }}
  strategy: 
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.portal.name }}
    spec:
      volumes:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
        imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.portal.port }}
          protocol: TCP
        env:
          - name: API_URL
          {{- if .Values.platform.tls }}
            value: {{ .Values.portal.properties.apiUrl | default (printf "https://%s/api" (.Values.platform.host | default .Values.global.nmaasDomain)) | quote }}
          {{- else }}
            value: {{ .Values.portal.properties.apiUrl | default (printf "http://%s/api" (.Values.platform.host | default .Values.global.nmaasDomain)) | quote }}
          {{- end }}
          - name: TOKEN_NAME
            value: {{ .Values.portal.properties.tokenName }}
          {{- if not .Values.global.demoDeployment }}
          - name: CAPTCHA_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.portal.properties.captchaKey.secret.name }}
                key: {{ .Values.portal.properties.captchaKey.secret.key }}
          {{- end }}  
      imagePullSecrets:
      - name: {{ .Values.global.registrysecret }}
{{- end -}}
