{{- if .Values.platform.adminPassword.literal }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.platform.adminPassword.secret.name | quote }}
data:
  {{ .Values.platform.adminPassword.secret.key | quote }}: {{ .Values.platform.adminPassword.literal | b64enc | quote }}
{{- end }}