{{- if .Values.platform.initscripts.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: nmaas-populate-job
spec:
  template:
    spec:
      containers:
      - name: pi
        image: "{{ .Values.platform.initscripts.image.repository }}:{{ .Values.platform.initscripts.image.tag }}"
        imagePullPolicy: {{ .Values.platform.initscripts.image.pullPolicy }}
        env:
          - name: PLATFORM_PORT
            value: "{{ .Values.platform.port }}"
          - name: PLATFORM_HOST
            value: "{{ .Values.platform.name }}"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.platform.adminPassword.secret.name }}
                key: {{ .Values.platform.adminPassword.secret.key }}
      restartPolicy: Never
{{- end }}
